### ISSUE TITLE
Latest release does not include .js file

### ISSUE THREAD

**Issue by gnesthenic** [AT41/StatRequirementChecklist#2]
Hi, thanks for continuing to work on this excellent plugin. I'd love to use the most recent version with the conversion fix, but I'm not sure how without a .js file on the release page. Hopefully this is the correct place to report this type of problem.

**Comment by AT41** [comment]
I've attached the compiled plugin and re-released the latest version (1.0.1). Thanks for letting me know!

**Comment by loweml** [comment]
Perfect, thank you!
